// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export type MultilinkStoryblok =
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      anchor?: string;
      rel?: string;
      title?: string;
      prep?: string;
      linktype: "story";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: any;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: any;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: any[];
        default_full_slug?: null | string;
        translated_slugs?: null | any[];
        [k: string]: any;
      };
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "url";
      rel?: string;
      title?: string;
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      email?: string;
      linktype: "email";
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "asset";
      [k: string]: any;
    };

export interface CallToActionStoryblok {
  text?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "callToAction";
  _uid: string;
  [k: string]: any;
}

export interface CasesStoryblok {
  sectionTitle?: SectionTitleStoryblok[];
  component: "cases";
  _uid: string;
  [k: string]: any;
}

export interface ContactStoryblok {
  sectionTitle?: SectionTitleStoryblok[];
  component: "contact";
  _uid: string;
  [k: string]: any;
}

export interface FeatureStoryblok {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: any;
}

export interface GridStoryblok {
  columns?: (
    | CallToActionStoryblok
    | CasesStoryblok
    | ContactStoryblok
    | FeatureStoryblok
    | GridStoryblok
    | HeroStoryblok
    | PageStoryblok
    | ProcessStoryblok
    | ProposalStoryblok
    | SectionTitleStoryblok
    | ServiceStoryblok
    | ServicesStoryblok
    | SponsorsStoryblok
    | TeamStoryblok
    | TeaserStoryblok
    | TestimonialsStoryblok
  )[];
  component: "grid";
  _uid: string;
  [k: string]: any;
}

export interface AssetStoryblok {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: any;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: any;
}

export interface HeroStoryblok {
  headline?: string;
  subtitle?: string;
  image: AssetStoryblok;
  callToAction?: CallToActionStoryblok[];
  component: "hero";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (
    | CallToActionStoryblok
    | CasesStoryblok
    | ContactStoryblok
    | FeatureStoryblok
    | GridStoryblok
    | HeroStoryblok
    | PageStoryblok
    | ProcessStoryblok
    | ProposalStoryblok
    | SectionTitleStoryblok
    | ServiceStoryblok
    | ServicesStoryblok
    | SponsorsStoryblok
    | TeamStoryblok
    | TeaserStoryblok
    | TestimonialsStoryblok
  )[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface ProcessStoryblok {
  sectionTitle?: SectionTitleStoryblok[];
  component: "process";
  _uid: string;
  [k: string]: any;
}

export interface ProposalStoryblok {
  title?: string;
  description?: string;
  callToAction?: CallToActionStoryblok[];
  component: "proposal";
  _uid: string;
  [k: string]: any;
}

export interface SectionTitleStoryblok {
  title?: string;
  description?: string;
  component: "sectionTitle";
  _uid: string;
  [k: string]: any;
}

export interface ServiceStoryblok {
  titleTop?: string;
  titleBottom?: string;
  image?: AssetStoryblok;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  style?: "gray" | "green" | "black";
  component: "service";
  _uid: string;
  [k: string]: any;
}

export interface ServicesStoryblok {
  sectionTitle?: SectionTitleStoryblok[];
  services?: ServiceStoryblok[];
  component: "services";
  _uid: string;
  [k: string]: any;
}

export type MultiassetStoryblok = {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: any;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: any;
}[];

export interface SponsorsStoryblok {
  logos?: MultiassetStoryblok;
  component: "sponsors";
  _uid: string;
  [k: string]: any;
}

export interface TeamStoryblok {
  sectionTitle?: SectionTitleStoryblok[];
  component: "team";
  _uid: string;
  [k: string]: any;
}

export interface TeaserStoryblok {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: any;
}

export interface TestimonialsStoryblok {
  sectionTitle?: SectionTitleStoryblok[];
  component: "testimonials";
  _uid: string;
  [k: string]: any;
}
